# src/constants/transactionCategories.py

"""
Transaction categories and related constants for the budget management system.
"""

# Available transaction categories
TRANSACTION_CATEGORIES = [
    "Food",
    "Transportation",
    "Entertainment",
    "Utilities",
    "Healthcare",
    "Shopping",
    "Housing",
    "Savings",
    "Investments",
    "Credit Card Payments",
    "Bank Payments",
    "Receipts",
    "Education",
    "Personal Care",
    "Miscellaneous",
]

# Keywords mapping for smart category detection
CATEGORY_KEYWORDS = {
    "Food": [
        "restaurant",
        "food truck",
        "cafe",
        "coffee shop",
        "lunch",
        "dinner",
        "breakfast",
        "meal",
        "pizza",
        "burger",
        "sushi",
        "starbucks",
        "mcdonald",
        "kfc",
        "cooking",
        "snack",
        "drink",
        "beverage",
        "beer",
        "wine",
        "alcohol",
        "bakery",
        "deli",
        "fast food",
        "takeout",
        "delivery",
        "uber eats",
        "doordash",
        "grab food",
        "foodpanda",
        "dining",
        "eat",
        "eating",
        "cuisine",
        "recipe",
        "buffet",
        "brunch",
    ],
    "Transportation": [
        "gas",
        "fuel",
        "uber",
        "taxi",
        "bus",
        "train",
        "subway",
        "metro",
        "car",
        "parking",
        "toll",
        "lyft",
        "grab",
        "vehicle",
        "transport",
        "flight",
        "airline",
        "airport",
        "maintenance",
        "repair",
        "oil change",
        "tire",
        "insurance",
        "registration",
        "motorbike",
        "motorcycle",
        "bicycle",
        "scooter",
        "public transport",
        "commute",
    ],
    "Entertainment": [
        "movie",
        "cinema",
        "theater",
        "theatre",
        "concert",
        "music",
        "spotify",
        "netflix",
        "gaming",
        "game",
        "book",
        "entertainment",
        "hobby",
        "sport",
        "gym",
        "fitness",
        "club",
        "bar",
        "party",
        "event",
        "ticket",
        "vacation",
        "travel",
        "hotel",
        "trip",
        "youtube",
        "subscription",
        "streaming",
        "disney",
        "amazon prime",
        "hulu",
    ],
    "Utilities": [
        "water",
        "gas bill",
        "internet",
        "phone",
        "mobile",
        "wifi",
        "cable",
        "utility",
        "bill",
        "power",
        "heating",
        "cooling",
        "trash",
        "sewer",
        "landline",
        "broadband",
        "telecom",
        "verizon",
        "at&t",
        "comcast",
    ],
    "Healthcare": [
        "doctor",
        "hospital",
        "pharmacy",
        "medicine",
        "medical",
        "health",
        "dentist",
        "insurance",
        "prescription",
        "clinic",
        "therapy",
        "vaccine",
        "checkup",
        "surgery",
        "treatment",
        "dental",
        "vision",
        "optical",
        "glasses",
        "contacts",
        "wellness",
        "healthcare",
        "physician",
        "specialist",
        "lab test",
        "x-ray",
    ],
    "Shopping": [
        "amazon",
        "ebay",
        "shopping",
        "grocery",
        "groceries",
        "supermarket",
        "market",
        "food shopping",
        "grocery shopping",
        "grocery store",
        "clothes",
        "clothing",
        "shoes",
        "fashion",
        "electronics",
        "gadget",
        "phone",
        "laptop",
        "computer",
        "furniture",
        "home goods",
        "department store",
        "mall",
        "online",
        "purchase",
        "buy",
        "target",
        "walmart",
        "costco",
        "best buy",
        "apple store",
        "retail",
        "store",
        "shop",
        "buy",
        "purchase",
    ],
    "Housing": [
        "rent",
        "mortgage",
        "property",
        "home",
        "house",
        "apartment",
        "condo",
        "hoa",
        "property tax",
        "home insurance",
        "maintenance",
        "repair",
        "renovation",
        "furniture",
        "appliance",
        "garden",
        "lawn",
        "cleaning",
        "security deposit",
        "utilities deposit",
        "home improvement",
    ],
    "Savings": [
        "savings",
        "deposit",
        "emergency fund",
        "rainy day",
        "saving account",
        "money market",
        "cd",
        "certificate of deposit",
        "piggy bank",
        "nest egg",
    ],
    "Investments": [
        "investment",
        "stock",
        "bond",
        "mutual fund",
        "etf",
        "crypto",
        "bitcoin",
        "trading",
        "broker",
        "dividend",
        "portfolio",
        "401k",
        "ira",
        "retirement",
        "robinhood",
        "fidelity",
        "charles schwab",
        "vanguard",
        "cryptocurrency",
    ],
    "Credit Card Payments": [
        "credit card",
        "visa",
        "mastercard",
        "amex",
        "american express",
        "discover",
        "payment",
        "credit",
        "card payment",
        "minimum payment",
        "cc payment",
        "chase",
        "capital one",
        "citi",
        "hsbc",
        "bank of america",
    ],
    "Bank Payments": [
        "bank",
        "transfer",
        "wire",
        "check",
        "atm",
        "fee",
        "service charge",
        "overdraft",
        "loan payment",
        "monthly payment",
        "banking",
        "withdrawal",
        "deposit fee",
        "maintenance fee",
        "transaction fee",
    ],
    "Receipts": [
        "receipt",
        "refund",
        "return",
        "reimbursement",
        "cashback",
        "rebate",
        "cash back",
        "money back",
        "store credit",
        "exchange",
        "electric",
        "electricity",
    ],
    "Education": [
        "school",
        "university",
        "college",
        "tuition",
        "education",
        "course",
        "class",
        "training",
        "workshop",
        "seminar",
        "book",
        "textbook",
        "supplies",
        "student",
        "learning",
        "certification",
        "exam",
        "test",
    ],
    "Personal Care": [
        "haircut",
        "salon",
        "spa",
        "beauty",
        "cosmetics",
        "skincare",
        "makeup",
        "personal care",
        "hygiene",
        "shampoo",
        "soap",
        "toothpaste",
        "grooming",
        "barber",
        "manicure",
        "pedicure",
        "facial",
        "massage",
        "self care",
    ],
}

# Default category for unmatched descriptions
DEFAULT_CATEGORY = "Miscellaneous"
